# Generated by Django 5.2.6 on 2025-09-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('numero_de_cuotas', models.IntegerField()),
                ('tasa_interes', models.FloatField()),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('cuota_mensual', models.FloatField(blank=True, null=True)),
                ('saldo_restante', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
    ]
