version: '3.8'

services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    restart: unless-stopped
    environment:
      - DD_API_KEY=4bd8e16462045529a97cd22d428fa9f6                 
      - DD_SITE=us5.datadoghq.com                
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "8125:8125/udp"   
      - "8126:8126"       

  db:
    image: lcguerra/liquidador-db
    container_name: liquidador_nomina_db
    environment:
      - POSTGRES_DB=liquidador_nomina
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: lcguerra/liquidador-backend
    container_name: liquidador_nomina_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/liquidador_nomina
      - DD_SERVICE=liquidador-backend
      - DD_ENV=local
      - DD_AGENT_HOST=dd-agent
      - DD_TRACE_AGENT_PORT=8126
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate && ddtrace-run python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    image: lcguerra/liquidador-frontend
    container_name: liquidador_nomina_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

volumes:
  postgres_data:
