# Generated by Django 5.2.6 on 2025-09-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHoraExtra',
            fields=[
                ('tipo_hora_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_tipo_hora', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_horas_extra',
            },
        ),
        migrations.CreateModel(
            name='HistorialNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('salario_bruto', models.FloatField()),
                ('deducciones', models.FloatField()),
                ('impuestos', models.FloatField()),
                ('auxilio_transporte', models.FloatField()),
                ('neto', models.FloatField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
            options={
                'db_table': 'historial_nomina',
            },
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_horas', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('tipo_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.tipohoraextra')),
            ],
            options={
                'db_table': 'horas_extras',
            },
        ),
    ]
