# Generated by Django 5.2.6 on 2025-09-28 20:02

import apps.empleados.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[apps.empleados.models.validate_cedula])),
                ('nombres', models.CharField(max_length=25, validators=[apps.empleados.models.validate_names])),
                ('apellidos', models.CharField(max_length=30, validators=[apps.empleados.models.validate_names])),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('salario_base', models.FloatField(validators=[apps.empleados.models.validate_salario_base])),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.cargo')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
